/* Generated by Windows 7 Compatible Struct Converter Tool */
#ifndef WIN7_STRUCT_CONVERTER_H
#define WIN7_STRUCT_CONVERTER_H

#include <stdint.h>
#include <stdbool.h>

typedef struct {
    int32_t temperature;
    float humidity;
    double pressure;
    bool valid;
} sensor_data_ext_t;

typedef struct {
    float temp_val;
    float humid_val;
    float press_val;
    bool is_valid;
} sensor_data_int_t;

// Conversion functions for sensor_data
int convert_sensor_data_ext_to_sensor_data_int(sensor_data_ext_t *external, sensor_data_int_t *internal, int recv_status);
int convert_sensor_data_int_to_sensor_data_ext(sensor_data_int_t *internal, sensor_data_ext_t *external, int recv_status);

#endif /* WIN7_STRUCT_CONVERTER_H */
