/* Generated by Windows 7 Compatible Struct Converter Tool */
#include "win7_struct_converter.h"

// Conversion functions

int convert_sensor_data_ext_to_sensor_data_int(sensor_data_ext_t *external, sensor_data_int_t *internal, int recv_status)
{
    if (!external || !internal) return -1;

    // Apply validation logic: external->valid && recv_status
    if (external->valid && recv_status) {
        internal->temp_val = external->temperature;
    } else {
        internal->temp_val = 0;  // Default value on validation failure
    }
    // Apply validation logic: recv_status == 1
    if (recv_status == 1) {
        internal->humid_val = external->humidity;
    } else {
        internal->humid_val = 0;  // Default value on validation failure
    }
    internal->press_val = press_convert_func(external->pressure);
    internal->is_valid = external->valid;
    return 0;
}

int convert_sensor_data_int_to_sensor_data_ext(sensor_data_int_t *internal, sensor_data_ext_t *external, int recv_status)
{
    if (!internal || !external) return -1;

    external->temperature = internal->temp_val;
    external->humidity = internal->humid_val;
    external->pressure = press_convert_func(internal->press_val);
    external->valid = internal->is_valid;
    return 0;
}
